#!/usr/bin/env sh
set -eu

usage() {
  cat <<'EOF'
Install Codex Council for the current user.

Usage:
  ./install.sh [options]

Options:
  --copy          Copy the skill instead of symlinking it.
  --force         Replace an existing installed skill or generated wrapper.
  --no-bin        Do not install the codex-council command wrapper.
  --bin-dir DIR   Install the command wrapper into DIR.
  -h, --help      Show this help.

Environment:
  CODEX_HOME              Codex home directory. Defaults to ~/.codex.
  CODEX_COUNCIL_BIN_DIR   Wrapper install directory. Defaults to ~/.local/bin.
EOF
}

mode="link"
force="0"
install_bin="1"
bin_dir="${CODEX_COUNCIL_BIN_DIR-}"

is_codex_council_skill_dir() {
  [ -f "$1/SKILL.md" ] && grep -q '^name: codex-council$' "$1/SKILL.md"
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --copy)
      mode="copy"
      ;;
    --force)
      force="1"
      ;;
    --no-bin)
      install_bin="0"
      ;;
    --bin-dir)
      if [ "$#" -lt 2 ]; then
        echo "install.sh: --bin-dir requires a directory" >&2
        exit 2
      fi
      bin_dir="$2"
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "install.sh: unknown option: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
  shift
done

script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
skill_source="$script_dir/skills/codex-council"
supervisor_path="$script_dir/scripts/codex_tui_supervisor.py"

if [ ! -f "$skill_source/SKILL.md" ]; then
  echo "install.sh: missing skill source: $skill_source/SKILL.md" >&2
  exit 1
fi

if [ ! -f "$supervisor_path" ]; then
  echo "install.sh: missing supervisor script: $supervisor_path" >&2
  exit 1
fi

codex_home="${CODEX_HOME-}"
if [ -z "$codex_home" ]; then
  if [ -z "${HOME-}" ]; then
    echo "install.sh: CODEX_HOME is unset and HOME is unavailable" >&2
    exit 1
  fi
  codex_home="$HOME/.codex"
fi
skills_dir="$codex_home/skills"
skill_dest="$skills_dir/codex-council"

mkdir -p "$skills_dir"

if [ -L "$skill_dest" ]; then
  current_target=$(readlink "$skill_dest")
  if [ "$current_target" = "$skill_source" ] && [ "$mode" = "link" ]; then
    echo "Skill already installed: $skill_dest -> $skill_source"
  elif [ "$force" = "1" ]; then
    rm "$skill_dest"
  else
    echo "install.sh: skill destination already exists: $skill_dest" >&2
    echo "Use --force to replace it." >&2
    exit 1
  fi
elif [ -e "$skill_dest" ]; then
  if [ "$force" = "1" ]; then
    if is_codex_council_skill_dir "$skill_dest"; then
      rm -rf "$skill_dest"
    else
      echo "install.sh: skill destination exists but does not look like codex-council: $skill_dest" >&2
      echo "Remove it manually or choose a different CODEX_HOME." >&2
      exit 1
    fi
  else
    echo "install.sh: skill destination already exists: $skill_dest" >&2
    echo "Use --force to replace it." >&2
    exit 1
  fi
fi

if [ ! -e "$skill_dest" ]; then
  if [ "$mode" = "copy" ]; then
    cp -R "$skill_source" "$skill_dest"
    echo "Installed skill copy: $skill_dest"
  else
    ln -s "$skill_source" "$skill_dest"
    echo "Installed skill symlink: $skill_dest -> $skill_source"
  fi
fi

if [ "$install_bin" = "1" ]; then
  if [ -z "$bin_dir" ]; then
    if [ -z "${HOME-}" ]; then
      echo "install.sh: CODEX_COUNCIL_BIN_DIR is unset and HOME is unavailable" >&2
      exit 1
    fi
    bin_dir="$HOME/.local/bin"
  fi
  mkdir -p "$bin_dir"
  wrapper_path="$bin_dir/codex-council"

  if [ -e "$wrapper_path" ] || [ -L "$wrapper_path" ]; then
    if [ -d "$wrapper_path" ] && [ ! -L "$wrapper_path" ]; then
      echo "install.sh: command wrapper path is a directory: $wrapper_path" >&2
      echo "Remove it manually or choose --bin-dir. --force does not remove directories." >&2
      exit 1
    elif [ -L "$wrapper_path" ]; then
      if [ "$force" != "1" ]; then
        echo "install.sh: command wrapper symlink already exists: $wrapper_path" >&2
        echo "Use --force to replace the symlink, or --no-bin to skip wrapper install." >&2
        exit 1
      fi
      rm -f "$wrapper_path"
    elif grep -q "Generated by codex-council install.sh" "$wrapper_path" 2>/dev/null; then
      :
    else
      echo "install.sh: command wrapper already exists and was not generated by this installer: $wrapper_path" >&2
      echo "Remove it manually, choose --bin-dir, or use --no-bin to skip wrapper install." >&2
      exit 1
    fi
  fi

  escaped_supervisor_path=$(printf '%s' "$supervisor_path" | sed 's/\\/\\\\/g; s/"/\\"/g; s/\$/\\$/g; s/`/\\`/g')
  tmp_wrapper="$wrapper_path.tmp.$$"
  cat > "$tmp_wrapper" <<EOF
#!/usr/bin/env sh
# Generated by codex-council install.sh
exec python3 "$escaped_supervisor_path" "\$@"
EOF
  chmod 755 "$tmp_wrapper"
  mv "$tmp_wrapper" "$wrapper_path"
  echo "Installed command wrapper: $wrapper_path"

  case ":${PATH-}:" in
    *":$bin_dir:"*) ;;
    *)
      echo "Note: $bin_dir is not on PATH. Add it to your shell profile to use 'codex-council' directly."
      ;;
  esac
fi

echo
echo "Done. Restart Codex or open a new Codex session so it discovers the codex-council skill."
